FROM ubuntu:22.04
COPY assets /
# ENV HTTPS_PROXY=http://192.168.1.81:10801
# ENV HTTP_PROXY=http://192.168.1.81:10801
# ENV ALL_PROXY=http://192.168.1.81:10801
RUN bash /localize-ubuntu/localize.sh \
    && apt install -y curl build-essential git libudev-dev libnm-dev libsystemd-dev protobuf-compiler \
    && apt autoremove -y \
    && apt autoclean -y
RUN bash -c "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain nightly -y"
RUN cp /localize-ubuntu/config /root/.cargo/config
ENV PATH=/root/.cargo/bin:$PATH
RUN git config --global --add safe.directory '*'
